name: "Continuous Deployment"
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: austral-ingsis
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
          # This 'build-args' lets us see the plain output so we can check if the value is printed or not
          build-args: |
            BUILDKIT_PROGRESS=plain
          push: true
          tags: |
            ghcr.io/austral-ingsis/docker-secrets:${{ steps.short-sha.outputs.sha }}